# Generated by Django 4.1.2 on 2024-06-21 20:56

from django.db import migrations
from django.contrib.auth.models import User


def populate_user(apps, schema_editor):
    Resume = apps.get_model('your_app_name', 'Resume')
    User = apps.get_model('auth', 'User')
    default_user = User.objects.first()  # Get the first user as the default user
    for resume in Resume.objects.all():
        if not resume.user:
            resume.user = default_user
            resume.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_resume_file_hash_resume_user'),
    ]

    operations = [
    ]
